# Maintainer: Jan Houben <jan@nexttrex.de>
# Contributor: Jesus Alvarez <jeezusjr at gmail dot com>
#
# This PKGBUILD was generated by the archzfs build scripts located at
#
# http://github.com/archzfs/archzfs
#
pkgname="spl-dkms"
pkgdesc="Solaris Porting Layer kernel modules."

pkgver=0.7.10
pkgrel=1
makedepends=()
arch=("x86_64")
url="http://zfsonlinux.org/"
source=("https://github.com/zfsonlinux/zfs/releases/download/zfs-${pkgver}/spl-${pkgver}.tar.gz"
        "60-spl-dkms-install.hook")
sha256sums=("9647e0fe9f19cd99746da3cc48b8de8903a66dacdccc82b45dbbb516606f4ff8"
            "15f71a9ceccf795cdac65743bee338e9987ec77e217721f32d55099be6ecf3d7")
license=("GPL")
depends=("spl-utils-common=${pkgver}" "dkms")
provides=("spl")
groups=("archzfs-dkms")
conflicts=('spl-dkms-git' 'spl-archiso-linux' 'spl-archiso-linux-git' 'spl-linux-hardened' 'spl-linux-hardened-git' 'spl-linux-lts' 'spl-linux-lts-git' 'spl-linux' 'spl-linux-git' 'spl-linux-vfio' 'spl-linux-vfio-git' 'spl-linux-zen' 'spl-linux-zen-git'  )

build() {
    cd "${srcdir}/spl-${pkgver}"
    ./autogen.sh
}

package() {
    # install alpm hook
    install -D -m 644 ${srcdir}/60-spl-dkms-install.hook ${pkgdir}/usr/share/libalpm/hooks/60-spl-dkms-install.hook
    dkmsdir="${pkgdir}/usr/src/spl-0.7.10"
    install -d "${dkmsdir}"
    cp -a ${srcdir}/spl-${pkgver}/. ${dkmsdir}
    cd "${dkmsdir}"
    find . -name ".git*" -print0 | xargs -0 rm -fr --
    scripts/dkms.mkconf -v 0.7.10 -f dkms.conf -n spl
    chmod g-w,o-w -R .
}
