# Maintainer: Jan Houben <jan@nexttrex.de>
# Contributor: Jesus Alvarez <jeezusjr at gmail dot com>
#
# This PKGBUILD was generated by the archzfs build scripts located at
#
# http://github.com/archzfs/archzfs
#
pkgname="spl-dkms"
pkgdesc="Solaris Porting Layer kernel modules."

pkgver=0.7.12
pkgrel=2
makedepends=()
arch=("x86_64")
url="http://zfsonlinux.org/"
source=("https://github.com/zfsonlinux/zfs/releases/download/zfs-${pkgver}/spl-${pkgver}.tar.gz")
sha256sums=("4709a06e913bbbeb634161a8b68c3f879e5b6040c6c0c09b1f51042b3178c274")
license=("GPL")
depends=("dkms")
provides=("spl" "spl-headers")
groups=("archzfs-dkms")
conflicts=("spl" "spl-headers")

build() {
    cd "${srcdir}/spl-${pkgver}"
    ./autogen.sh
}

package() {
    dkmsdir="${pkgdir}/usr/src/spl-${pkgver}"
    install -d "${dkmsdir}"
    cp -a ${srcdir}/spl-${pkgver}/. ${dkmsdir}
    cd "${dkmsdir}"
    find . -name ".git*" -print0 | xargs -0 rm -fr --
    scripts/dkms.mkconf -v ${pkgver} -f dkms.conf -n spl
    chmod g-w,o-w -R .
}
